//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by LLVMPDBCOM.rc
//
#define IDS_PROJNAME                    100
#define IDR_LLVMCOM                     101
#define IDR_LLVMBUMPPTRALLOCATOR        102
#define IDR_LLVMPDBFILEBUILDER          103
#define IDR_LLVMINFOSTREAMBUILDER       104
#define IDR_LLVMDBISTREAMBUILDER        105
#define IDR_LLVMTPISTREAMBUILDER        106
#define IDR_LLVMPDBSTRINGTABLEBUILDER   107
#define IDR_LLVMDBIMODULEDESCRIPTORBUILDER 108
#define IDR_LLVMDEBUGSTRINGTABLESUBSECTION 109
#define IDR_LLVMDEBUGCHECKSUMSSUBSECTION 110
#define IDR_LLVMDEBUGLINESSUBSECTION    111
#define IDR_LLVMDEBUGSUBSECTION         112
#define IDR_LLVMMSFBUILDER              113
#define IDR_LLVMPDBUTILITIES            114
#define IDR_LLVMGSISTREAMBUILDER        115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         201
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
